const CONSTANT = {
  TOKEN: '__gl_ui_tvl__',
  THEME_MODE: 't_m',
  COLOR_SCHEME: 'p_m',
  SIDER_WIDTH_WHEN_EXPAND: 200,
  SIDER_WIDTH: 60,
  LANGUAGE_STORAGE_KEY: 'LANGUAGE',
  FONT_FAMILY: 'f_t',
  RESPONSE_SUCCESS_CODE: 0,
  REDIRECT_KEY_PARAMS_NAME: 'target',
};

export default CONSTANT;
